<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  min_width,
  max_width,
  minic,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  prob,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  seqfrac,
  strands,
  priors_file,
  reason_for_stopping,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT minic (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT prob (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT seqfrac (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="4.11.2" release="Thu May 05 14:58:55 2016 -0700">
<training_set datafile="/bigdata/stajichlab/shared/projects/ZyGoLife/Entomophthora/E_muscae/Entomophthora_muscae_UCB/annotate/Massospora_cicadina_6FC.v_medaka/antismash_local/meme/MCIC6FC_015428/+10_-09/promoters.fasta" length="20">
<alphabet name="DNA" like="dna">
<letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
<letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
<letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
<letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
<letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
<letter id="V" symbol="V" equals="ACG" name="Not T"/>
<letter id="H" symbol="H" equals="ACT" name="Not G"/>
<letter id="D" symbol="D" equals="AGT" name="Not C"/>
<letter id="B" symbol="B" equals="CGT" name="Not A"/>
<letter id="M" symbol="M" equals="AC" name="Amino"/>
<letter id="R" symbol="R" equals="AG" name="Purine"/>
<letter id="W" symbol="W" equals="AT" name="Weak"/>
<letter id="S" symbol="S" equals="CG" name="Strong"/>
<letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
<letter id="K" symbol="K" equals="GT" name="Keto"/>
</alphabet>
<sequence id="sequence_0" name="MCIC6FC_015416" length="60" weight="1.000000" />
<sequence id="sequence_1" name="MCIC6FC_015417" length="132" weight="1.000000" />
<sequence id="sequence_2" name="MCIC6FC_015418" length="125" weight="1.000000" />
<sequence id="sequence_3" name="MCIC6FC_015419+MCIC6FC_015420" length="258" weight="1.000000" />
<sequence id="sequence_4" name="MCIC6FC_015421" length="149" weight="1.000000" />
<sequence id="sequence_5" name="MCIC6FC_015422+MCIC6FC_015423" length="247" weight="1.000000" />
<sequence id="sequence_6" name="MCIC6FC_015424+MCIC6FC_015425" length="494" weight="1.000000" />
<sequence id="sequence_7" name="MCIC6FC_015426" length="182" weight="1.000000" />
<sequence id="sequence_8" name="MCIC6FC_015427" length="467" weight="1.000000" />
<sequence id="sequence_9" name="MCIC6FC_015428+MCIC6FC_015429__ANCHOR" length="316" weight="1.000000" />
<sequence id="sequence_10" name="MCIC6FC_015430+MCIC6FC_015431" length="256" weight="1.000000" />
<sequence id="sequence_11" name="MCIC6FC_015432" length="369" weight="1.000000" />
<sequence id="sequence_12" name="MCIC6FC_015433+MCIC6FC_015434" length="294" weight="1.000000" />
<sequence id="sequence_13" name="MCIC6FC_015435" length="77" weight="1.000000" />
<sequence id="sequence_14" name="MCIC6FC_015436" length="331" weight="1.000000" />
<sequence id="sequence_15" name="MCIC6FC_015437+MCIC6FC_015438" length="202" weight="1.000000" />
<sequence id="sequence_16" name="MCIC6FC_015439" length="136" weight="1.000000" />
<sequence id="sequence_17" name="MCIC6FC_015440" length="187" weight="1.000000" />
<sequence id="sequence_18" name="MCIC6FC_015441" length="145" weight="1.000000" />
<sequence id="sequence_19" name="MCIC6FC_015442+MCIC6FC_015443" length="359" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="A">0.232</value>
<value letter_id="C">0.268</value>
<value letter_id="G">0.268</value>
<value letter_id="T">0.232</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme /bigdata/stajichlab/shared/projects/ZyGoLife/Entomophthora/E_muscae/Entomophthora_muscae_UCB/annotate/Massospora_cicadina_6FC.v_medaka/antismash_local/meme/MCIC6FC_015428/+10_-09/promoters.fasta -oc /bigdata/stajichlab/shared/projects/ZyGoLife/Entomophthora/E_muscae/Entomophthora_muscae_UCB/annotate/Massospora_cicadina_6FC.v_medaka/antismash_local/meme/MCIC6FC_015428/+10_-09 -dna -nostatus -mod anr -nmotifs 1 -minw 6 -maxw 12 -revcomp -evt 1.0e+005 </command_line>
<host>fv-az60</host>
<type>anr</type>
<nmotifs>1</nmotifs>
<evalue_threshold>100000</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<use_llr>0</use_llr>
<min_width>6</min_width>
<max_width>12</max_width>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<substring>yes</substring>
<minsites>2</minsites>
<maxsites>50</maxsites>
<wnsites>0.8</wnsites>
<spmap>uni</spmap>
<spfuzz>0.5</spfuzz>
<prior>dirichlet</prior>
<beta>0.01</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_sequences>20</num_sequences>
<num_positions>4786</num_positions>
<seed>0</seed>
<ctfrac>-1</ctfrac>
<maxwords>-1</maxwords>
<strands>both</strands>
<priors_file></priors_file>
<reason_for_stopping>Stopped because requested number of motifs (1) found.</reason_for_stopping>
<background_frequencies source="dataset with add-one prior applied">
<alphabet_array>
<value letter_id="A">0.232</value>
<value letter_id="C">0.268</value>
<value letter_id="G">0.268</value>
<value letter_id="T">0.232</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="1" width="12" sites="13" ic="15.4" re="15.7" llr="141" e_value="2.2e+001" bayes_threshold="8.98394" elapsed_time="5.014363">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">199</value>
<value letter_id="C">-1035</value>
<value letter_id="G">-1035</value>
<value letter_id="T">-159</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">199</value>
<value letter_id="C">-1035</value>
<value letter_id="G">-1035</value>
<value letter_id="T">-159</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">210</value>
<value letter_id="C">-1035</value>
<value letter_id="G">-1035</value>
<value letter_id="T">-1035</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">210</value>
<value letter_id="C">-1035</value>
<value letter_id="G">-1035</value>
<value letter_id="T">-1035</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">157</value>
<value letter_id="C">-1035</value>
<value letter_id="G">20</value>
<value letter_id="T">-1035</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1035</value>
<value letter_id="C">152</value>
<value letter_id="G">-1035</value>
<value letter_id="T">-1</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-159</value>
<value letter_id="C">179</value>
<value letter_id="G">-1035</value>
<value letter_id="T">-1035</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1035</value>
<value letter_id="C">-1035</value>
<value letter_id="G">120</value>
<value letter_id="T">73</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-159</value>
<value letter_id="C">-1035</value>
<value letter_id="G">120</value>
<value letter_id="T">40</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1035</value>
<value letter_id="C">137</value>
<value letter_id="G">-1035</value>
<value letter_id="T">40</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">121</value>
<value letter_id="C">-180</value>
<value letter_id="G">52</value>
<value letter_id="T">-1035</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">40</value>
<value letter_id="C">-1035</value>
<value letter_id="G">-80</value>
<value letter_id="T">121</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.923077</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.076923</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.923077</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.076923</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">1.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">1.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.692308</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.307692</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.769231</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.230769</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.076923</value>
<value letter_id="C">0.923077</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.615385</value>
<value letter_id="T">0.384615</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.076923</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.615385</value>
<value letter_id="T">0.307692</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.692308</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.307692</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.538462</value>
<value letter_id="C">0.076923</value>
<value letter_id="G">0.384615</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.307692</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.153846</value>
<value letter_id="T">0.538462</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
AAAA[AG][CT]C[GT][GT][CT][AG][TA]
</regular_expression>
<contributing_sites>
<contributing_site sequence_id="sequence_1" position="106" strand="minus" pvalue="1.51e-07" >
<left_flank>CTGTGCAGGA</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TCATCGCCGG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_1" position="91" strand="plus" pvalue="6.65e-07" >
<left_flank>CAGGCGAAAA</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
</site>
<right_flank>TGAACGCCGG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_17" position="23" strand="minus" pvalue="8.89e-07" >
<left_flank>CAAGGCAAAA</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>CTCTGCAGGC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_9" position="57" strand="minus" pvalue="8.89e-07" >
<left_flank>TCCCCAACGG</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
</site>
<right_flank>GGAATATATG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_2" position="31" strand="plus" pvalue="2.96e-06" >
<left_flank>TTGAACAGGG</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>CTTGCATGTC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_6" position="127" strand="plus" pvalue="3.48e-06" >
<left_flank>GGATTTTCTA</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>AAATCAGCAG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_17" position="9" strand="plus" pvalue="5.01e-06" >
<left_flank>CAGATAGAG</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>AGATGCAGGC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_19" position="152" strand="minus" pvalue="5.33e-06" >
<left_flank>TTTAAGCTAC</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>GCTCATCGCC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_11" position="23" strand="minus" pvalue="8.96e-06" >
<left_flank>TGCTCACCAC</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>GCCACAGGTC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_14" position="303" strand="plus" pvalue="1.04e-05" >
<left_flank>TTTACAGAGT</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TGGGTAATGA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_6" position="158" strand="minus" pvalue="1.11e-05" >
<left_flank>CACGAAAGTG</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
</site>
<right_flank>AATTTTAACC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_8" position="62" strand="minus" pvalue="1.26e-05" >
<left_flank>ACTGTGGCTG</left_flank>
<site>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>CGCGGGCAAG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_8" position="207" strand="minus" pvalue="2.14e-05" >
<left_flank>GGCAGCGTGA</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
</site>
<right_flank>ATTGTCTTGG</right_flank>
</contributing_site>
</contributing_sites>
</motif>
</motifs>
<scanned_sites_summary p_thresh="0.0001">
<scanned_sites sequence_id="sequence_0" pvalue="3.17e-01" num_sites="0"></scanned_sites>
<scanned_sites sequence_id="sequence_1" pvalue="3.66e-05" num_sites="2"><scanned_site motif_id="motif_1" strand="plus" position="91" pvalue="6.65e-07"/>
<scanned_site motif_id="motif_1" strand="minus" position="106" pvalue="1.51e-07"/>
</scanned_sites>
<scanned_sites sequence_id="sequence_2" pvalue="6.75e-04" num_sites="1"><scanned_site motif_id="motif_1" strand="plus" position="31" pvalue="2.96e-06"/>
</scanned_sites>
<scanned_sites sequence_id="sequence_3" pvalue="4.35e-01" num_sites="0"></scanned_sites>
<scanned_sites sequence_id="sequence_4" pvalue="1.78e-01" num_sites="0"></scanned_sites>
<scanned_sites sequence_id="sequence_5" pvalue="4.57e-01" num_sites="0"></scanned_sites>
<scanned_sites sequence_id="sequence_6" pvalue="3.36e-03" num_sites="2"><scanned_site motif_id="motif_1" strand="plus" position="127" pvalue="3.48e-06"/>
<scanned_site motif_id="motif_1" strand="minus" position="158" pvalue="1.11e-05"/>
</scanned_sites>
<scanned_sites sequence_id="sequence_7" pvalue="5.25e-01" num_sites="0"></scanned_sites>
<scanned_sites sequence_id="sequence_8" pvalue="1.15e-02" num_sites="2"><scanned_site motif_id="motif_1" strand="minus" position="62" pvalue="1.26e-05"/>
<scanned_site motif_id="motif_1" strand="minus" position="207" pvalue="2.14e-05"/>
</scanned_sites>
<scanned_sites sequence_id="sequence_9" pvalue="5.42e-04" num_sites="1"><scanned_site motif_id="motif_1" strand="minus" position="57" pvalue="8.89e-07"/>
</scanned_sites>
<scanned_sites sequence_id="sequence_10" pvalue="7.08e-01" num_sites="0"></scanned_sites>
<scanned_sites sequence_id="sequence_11" pvalue="6.40e-03" num_sites="1"><scanned_site motif_id="motif_1" strand="minus" position="23" pvalue="8.96e-06"/>
</scanned_sites>
<scanned_sites sequence_id="sequence_12" pvalue="2.01e-01" num_sites="0"></scanned_sites>
<scanned_sites sequence_id="sequence_13" pvalue="6.94e-01" num_sites="0"></scanned_sites>
<scanned_sites sequence_id="sequence_14" pvalue="6.62e-03" num_sites="1"><scanned_site motif_id="motif_1" strand="plus" position="303" pvalue="1.04e-05"/>
</scanned_sites>
<scanned_sites sequence_id="sequence_15" pvalue="6.25e-01" num_sites="0"></scanned_sites>
<scanned_sites sequence_id="sequence_16" pvalue="1.93e-01" num_sites="0"></scanned_sites>
<scanned_sites sequence_id="sequence_17" pvalue="3.13e-04" num_sites="2"><scanned_site motif_id="motif_1" strand="plus" position="9" pvalue="5.01e-06"/>
<scanned_site motif_id="motif_1" strand="minus" position="23" pvalue="8.89e-07"/>
</scanned_sites>
<scanned_sites sequence_id="sequence_18" pvalue="2.38e-01" num_sites="0"></scanned_sites>
<scanned_sites sequence_id="sequence_19" pvalue="3.71e-03" num_sites="1"><scanned_site motif_id="motif_1" strand="minus" position="152" pvalue="5.33e-06"/>
</scanned_sites>
</scanned_sites_summary>
</MEME>
